### ISSUE TITLE
Plugin could not be loaded

### ISSUE THREAD

**Issue by qingtianyu11111** [carvelli/PalacePal#15]
Plugin could not be loaded: System.TypeLoadException - Could not load type 'System.Text.Json.Serialization.JsonRequiredAttribute' from assembly 'System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

**Comment by carvelli** [comment]
I'm sorry, which version of Dalamud are you using? The plugin references `System.Text.Json, Version=7.0.0.0`, so I don't understand why this would be the wrong version.

**Comment by qingtianyu11111** [comment]
> 
1003.1.0.2
so Isn't my version the latest version？

**Comment by carvelli** [comment]
It sounds more as if you're playing the CN or KR version of the game, which are using .NET 6 as far as I know. `System.Text.Json` is part of the .NET runtime, so I wouldn't know why yours is trying to load an older version otherwise.

Maybe there is a `System.Text.Json.dll` somewhere in your dalamud folder, which it is loading instead, but I don't know if that's a thing.

**Comment by qingtianyu11111** [comment]
> 

Yes, I'm using CN's client, maybe this is a CN incompatibility issue?

**Comment by carvelli** [comment]
The CN version won't work until they're updated for .NET 7, which is (probably?) in the 6.3 update, at least that's when the global version was updated.
