### ISSUE TITLE
Cannot connect to the Remote API as the key doesn't exist in the dictionary

### ISSUE THREAD

**Issue by thakyZ** [carvelli/PalacePal#2]
Getting this error
![image](https://user-images.githubusercontent.com/950594/199560643-563d7465-3a5d-4412-ad88-0f4932bf0ae9.png)

I don't think getting a remote account via the URL of your API is a good way to look through a dictionary. Might I recommend doing something like how Mare did by having you link your Lodestone account and then in the config (client side) store the ID for that character based on name or something?

**Comment by carvelli** [comment]
Fixed in 1.15+ (b8fa8a24f0b74af72c022073d9ab0958cbc2333e), you need to upgrade your client for it to work.

Re - dictionary: It's mostly built that way to support different API endpoints which don't share the same database (e.g. pre-release testing for the reverse proxy setup, local debugging, but also if you want to run your own instance for whatever reason). The account ids are randomly-generated and per-instance; there's no character data associated with it - neither is there a reason for character ids to be saved either. I want to know how many people use the plugin, but there's no difference to me /who/ uses it currently.

Accounts are mostly for tracking statistics at the moment (how many people have seen a specific trap/coffer) so that in the future, we could for example publish a map for different floors which have the relevant locations marked, and be reasonably confident that they're not wrong due to some random client fuckup. (That said, generating such a map isn't trivial either, but that's a problem for future-me or someone else).
